schema_version = "1.0.0"
id = "fire_maze"
name = "FireMaze"
version = "2.0.1"
tagline = "Random maze generator with tiled construction"
maintainer = "FireRat666"
blender_version_min = "4.2.0"
license = [
    "SPDX:GPL-3.0-or-later",
]
permissions = []
type = "add-on"
